# graph.py
"""Graph definition, state schema, prompts, and agent nodes.

This module isolates the LangGraph workflow from the HTTP layer.
"""

from typing import Annotated, TypedDict
import operator
import logging
import contextvars

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage, ToolMessage
from langgraph.graph import END, START, StateGraph

from .agents import initialize_agent_models
from .tools import write_to_file, list_files, read_file

logger = logging.getLogger(__name__)

# Request-scoped context variable to dynamically bind the active target workspace path
workspace_ctx = contextvars.ContextVar("workspace_dir", default="./workspace")

# ---------------------------------------------------------------------------
# Prompts (Personas)
# ---------------------------------------------------------------------------
class Personas:
    """System prompts for the specialized agents."""

    PRODUCT_MANAGER_SYSTEM = (
        "You are an expert Frontend Product Manager and UI/UX Designer with deep expertise "
        "in modern web design, responsive layouts, and user experience.\n\n"
        "Your task: Analyze the user's interface request and produce a crystal-clear technical specification.\n\n"
        "For NEW projects, outline:\n"
        "1. **Component Structure**: Break down the interface into reusable components (header, hero, cards, etc.)\n"
        "2. **Layout & Responsiveness**: Describe grid/flexbox layouts, breakpoints, and mobile adaptation\n"
        "3. **Styling Design Tokens**: Color palette, typography, spacing, shadows, border-radius\n"
        "4. **Interactive Behaviors**: Hover effects, animations, state changes, and user interactions\n"
        "5. **Content Requirements**: What text, images, or data elements are needed\n\n"
        "For UPDATES to existing projects:\n"
        "1. First, analyze the current file structure using the tools available\n"
        "2. Identify what exists and what needs modification or addition\n"
        "3. Provide precise, actionable update instructions\n\n"
        "OUTPUT FORMAT: Be specific, concise, and ready for a developer to implement."
    )

    CODER_SYSTEM = (
        "You are an elite Frontend Software Engineer with mastery in HTML5, modern CSS (Grid, Flexbox, animations), "
        "and vanilla JavaScript.\n\n"
        "Your objective: Generate production-ready, single-file HTML/CSS/JS applications.\n\n"
        "CRITICAL WORKFLOW (You MUST follow this sequence before writing any source code files):\n"
        "1. Inspect existing files using `list_files` and `read_file` tools if updating or integrating.\n"
        "2. **Create Plan**: Call `write_to_file` to create `plan.md` inside the workspace outlining the implementation design, layout decisions, and dependencies.\n"
        "3. **Create Tasks Checklist**: Call `write_to_file` to create `tasks.md` inside the workspace containing a structured checklist of all source files to be created/updated.\n"
        "4. **Write Code**: Implement files and use `write_to_file` to write source code files.\n"
        "5. **Update Tasks Checklist**: Modify `tasks.md` to check off (`[x]`) all completed files and tasks.\n"
        "6. Do NOT just output code as text in chat—always save the plan, tasks, and code files to the workspace using the tools.\n\n"
        "OUTPUT: Use tools to write files directly. Provide inline explanations only for complex logic."
    )

    @staticmethod
    def get_coder_user_prompt(specification: str) -> str:
        return (
            f"Build or update code based on this specification:\n\n"
            f"{specification}\n\n"
            "INSTRUCTIONS:\n"
            "1. Read any existing files using `read_file` to understand the current state if relevant.\n"
            "2. **CRITICAL FIRST STEP**: Call `write_to_file` to create `plan.md` (detailing implementation design) and `tasks.md` (checklist of files/tasks) inside the workspace folder BEFORE writing any code files.\n"
            "3. Create or modify the necessary code files and save them using `write_to_file`.\n"
            "4. Update `tasks.md` using `write_to_file` to check off (`[x]`) completed items.\n"
            "5. Keep code clean, well-commented, and properly formatted.\n\n"
            "CRITICAL: Always use `write_to_file` to save your work (planning, checklist, and code files) to the workspace!"
        )

# ---------------------------------------------------------------------------
# State Schema
# ---------------------------------------------------------------------------
class TeamState(TypedDict):
    """Shared memory passed between agents.

    - ``messages``: Message history (auto‑appended via ``operator.add``).
    - ``specification``: UI spec generated by the Product Manager.
    - ``next_agent``: Identifier of the next node to execute.
    - ``workspace``: Custom target directory for file reads/writes.
    """

    messages: Annotated[list[BaseMessage], operator.add]
    specification: str
    next_agent: str
    workspace: str

# ---------------------------------------------------------------------------
# Agent Nodes (Workers)
# ---------------------------------------------------------------------------
# Initialise LLMs once – they are reused by both nodes.
pm_llm, coder_llm = initialize_agent_models()


# ---------------------------------------------------------------------------
# Agent Nodes (Workers)
# ---------------------------------------------------------------------------
# Initialize LLMs once – they are reused by both nodes.
pm_llm, coder_llm = initialize_agent_models()


async def pm_agent(state: TeamState) -> dict:
    """Product Manager node – analyzes request and creates a UI specification.
    
    Args:
        state: Current team state containing user messages.
        
    Returns:
        Updated state with specification and next agent assignment.
        
    Raises:
        Exception: If LLM invocation fails (caught by graph executor).
    """
    try:
        user_messages = state["messages"]
        logger.info(f"PM Agent: Processing user request")
        
        response = await pm_llm.ainvoke([
            SystemMessage(content=Personas.PRODUCT_MANAGER_SYSTEM)
        ] + user_messages)
        
        logger.info(f"PM Agent: Generated specification ({len(response.content)} chars)")
        
        return {
            "messages": [AIMessage(content=response.content, name="ProductManager")],
            "specification": response.content,
            "next_agent": "coder",
        }
    except Exception as e:
        logger.error(f"PM Agent failed: {str(e)}", exc_info=True)
        raise


async def coder_agent(state: TeamState) -> dict:
    """Coder node – generates frontend code and writes to workspace.
    
    Args:
        state: Current team state containing specification and workspace path.
        
    Returns:
        Updated state with generated code and end signal.
        
    Raises:
        Exception: If LLM invocation or file operations fail.
    """
    # Dynamically bind request-scoped workspace directory
    workspace = state.get("workspace", "./workspace")
    token = workspace_ctx.set(workspace)
    
    try:
        logger.info(f"Coder Agent: Starting code generation in workspace: {workspace}")
        
        spec = state["specification"]
        system_instruction = SystemMessage(content=Personas.CODER_SYSTEM)
        user_prompt = HumanMessage(content=Personas.get_coder_user_prompt(spec))
        
        # Bind the filesystem tools to the coder LLM
        coder_with_tools = coder_llm.bind_tools([write_to_file, list_files, read_file])
        
        messages = [system_instruction, user_prompt]
        response = await coder_with_tools.ainvoke(messages)
        
        # Agentic loop: execute tool calls in response
        tool_iteration = 0
        max_iterations = 10  # Prevent infinite loops
        
        while response.tool_calls and tool_iteration < max_iterations:
            tool_iteration += 1
            logger.debug(f"Coder Agent: Tool call iteration {tool_iteration}")
            
            messages.append(response)
            tool_messages = []
            
            for tool_call in response.tool_calls:
                tool_name = tool_call["name"]
                tool_args = tool_call["args"]
                
                logger.debug(f"Coder Agent: Executing tool '{tool_name}' with args: {list(tool_args.keys())}")
                
                try:
                    if tool_name == "write_to_file":
                        tool_result = await write_to_file.ainvoke(tool_args)
                    elif tool_name == "list_files":
                        tool_result = await list_files.ainvoke(tool_args)
                    elif tool_name == "read_file":
                        tool_result = await read_file.ainvoke(tool_args)
                    else:
                        tool_result = f"Error: Tool '{tool_name}' not found."
                        logger.warning(f"Coder Agent: Unknown tool '{tool_name}'")
                    
                    logger.debug(f"Coder Agent: Tool result: {str(tool_result)[:100]}...")
                        
                except Exception as e:
                    logger.error(f"Coder Agent: Tool execution failed: {str(e)}", exc_info=True)
                    tool_result = f"Error executing tool: {str(e)}"
                    
                tool_messages.append(ToolMessage(
                    content=str(tool_result),
                    tool_call_id=tool_call["id"],
                    name=tool_name
                ))
                
            messages.extend(tool_messages)
            
            # Invoke coder LLM again with tool results
            response = await coder_with_tools.ainvoke(messages)
        
        if tool_iteration >= max_iterations:
            logger.warning(f"Coder Agent: Reached max iterations ({max_iterations}), stopping")
        
        logger.info(f"Coder Agent: Code generation completed after {tool_iteration} tool iterations")
        
        return {
            "messages": [AIMessage(content=response.content, name="Coder")],
            "next_agent": "end",
        }
        
    except Exception as e:
        logger.error(f"Coder Agent failed: {str(e)}", exc_info=True)
        raise
    finally:
        workspace_ctx.reset(token)


def routing_router(state: TeamState) -> str:
    """Conditional router – decides the next node based on ``next_agent`` flag.
    
    Args:
        state: Current team state.
        
    Returns:
        Name of next node ("coder") or END signal.
    """
    next_agent = state.get("next_agent", "end")
    logger.debug(f"Routing: next_agent = {next_agent}")
    
    if next_agent == "coder":
        return "coder"
    return END


# ---------------------------------------------------------------------------
# Build the LangGraph
# ---------------------------------------------------------------------------
builder = StateGraph(TeamState)
builder.add_node("pm", pm_agent)
builder.add_node("coder", coder_agent)
builder.add_edge(START, "pm")
builder.add_conditional_edges(
    "pm",
    routing_router,
    {
        "coder": "coder",
        END: END,
    },
)
builder.add_edge("coder", END)

# Compiled graph – used by the FastAPI route layer.
graph = builder.compile()

logger.info("LangGraph compiled and ready")
