# graph.py
"""Graph definition, state schema, prompts, and agent nodes.

This module isolates the LangGraph workflow from the HTTP layer.
"""

from typing import Annotated, TypedDict
import operator
import os
import contextvars

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage, ToolMessage
from langgraph.graph import END, START, StateGraph
from langchain_core.tools import tool

from .agents import initialize_agent_models
from .mcp_server import write_to_file as mcp_write_to_file, list_files as mcp_list_files, read_file as mcp_read_file

# Request-scoped context variable to dynamically bind the active target workspace path
workspace_ctx = contextvars.ContextVar("workspace_dir", default="./workspace")

@tool
async def write_to_file(path: str, content: str) -> str:
    """Writes code to a file in the workspace.
    
    Args:
        path: The relative path of the file (e.g. 'index.html').
        content: The complete raw code content.
    """
    base_dir = os.path.abspath(workspace_ctx.get())
    full_path = os.path.normpath(os.path.join(base_dir, path))
    
    # Security: Stay in the workspace folder
    if not full_path.startswith(base_dir):
        return "Error: Access denied."
        
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w") as f:
        f.write(content)
    return f"File {path} created/updated successfully."

@tool
async def list_files(directory: str = ".") -> list[str]:
    """Lists files in the workspace.
    
    Args:
        directory: The sub-directory to list (default is root '.').
    """
    base_dir = os.path.abspath(workspace_ctx.get())
    target_dir = os.path.normpath(os.path.join(base_dir, directory))
    
    if not target_dir.startswith(base_dir):
        return ["Error: Access denied."]
        
    if not os.path.exists(target_dir):
        return []
        
    return os.listdir(target_dir)

@tool
async def read_file(path: str) -> str:
    """Reads the content of a file in the workspace to understand existing code.
    
    Args:
        path: The relative path of the file (e.g. 'index.html').
    """
    base_dir = os.path.abspath(workspace_ctx.get())
    full_path = os.path.normpath(os.path.join(base_dir, path))
    
    if not full_path.startswith(base_dir):
        return "Error: Access denied."
        
    if not os.path.exists(full_path):
        return f"Error: File {path} does not exist."
        
    with open(full_path, "r") as f:
        return f.read()

# ---------------------------------------------------------------------------
# State Schema
# ---------------------------------------------------------------------------
class TeamState(TypedDict):
    """Shared memory passed between agents.

    - ``messages``: Message history (auto‑appended via ``operator.add``).
    - ``specification``: UI spec generated by the Product Manager.
    - ``next_agent``: Identifier of the next node to execute.
    - ``workspace``: Custom target directory for file reads/writes.
    """

    messages: Annotated[list[BaseMessage], operator.add]
    specification: str
    next_agent: str
    workspace: str

# ---------------------------------------------------------------------------
# Prompts (Personas)
# ---------------------------------------------------------------------------
class Personas:
    """System prompts for the specialized agents."""

    PRODUCT_MANAGER_SYSTEM = (
        "You are an expert Frontend Product Manager and UI/UX Designer.\n\n"
        "Analyze the user's interface request. If the user wants to add or update features "
        "in an existing project workspace, analyze the current file structure and describe "
        "precisely what layout changes, additions, or code updates need to be made.\n"
        "Otherwise, outline a brand-new technical specification:\n"
        "1. Component structure and layout hierarchy.\n"
        "2. Styling requirements, responsiveness, and color themes.\n"
        "3. Interactive behavior, events, and state management logic needed."
    )

    CODER_SYSTEM = (
        "You are an elite Frontend Software Engineer.\n\n"
        "Your objective is to generate functional, high-quality frontends.\n"
        "You can inspect existing workspace files using `list_files` and `read_file` to understand "
        "the current codebase before adding or updating features.\n"
        "Crucially, you MUST use the `write_to_file` tool to write the finalized "
        "pristine code directly to the workspace (e.g., 'index.html'). "
        "Do not simply talk about the code or output code blocks in text; "
        "you must call the tool to finalize the workspace."
    )

    @staticmethod
    def get_coder_user_prompt(specification: str) -> str:
        return (
            f"Build or update pristine, modern, functional code based strictly on the following UI specification:\n\n"
            f"{specification}\n\n"
            "If updating an existing file, read it first, then output the complete updated code block. "
            "Enclose code snippets cleanly in markdown codeblocks. Remember to write the code via the write_to_file tool!"
        )

# ---------------------------------------------------------------------------
# Agent Nodes (Workers)
# ---------------------------------------------------------------------------
# Initialise LLMs once – they are reused by both nodes.
pm_llm, coder_llm = initialize_agent_models()

async def pm_agent(state: TeamState) -> dict:
    """Product Manager node – creates a UI specification."""
    user_messages = state["messages"]
    response = await pm_llm.ainvoke([
        SystemMessage(content=Personas.PRODUCT_MANAGER_SYSTEM)
    ] + user_messages)
    return {
        "messages": [AIMessage(content=response.content, name="ProductManager")],
        "specification": response.content,
        "next_agent": "coder",
    }

async def coder_agent(state: TeamState) -> dict:
    """Coder node – generates frontend code and writes it to the filesystem."""
    # Dynamically bind request-scoped workspace directory
    workspace = state.get("workspace", "./workspace")
    token = workspace_ctx.set(workspace)
    
    try:
        spec = state["specification"]
        system_instruction = SystemMessage(content=Personas.CODER_SYSTEM)
        user_prompt = HumanMessage(content=Personas.get_coder_user_prompt(spec))
        
        # Bind the write_to_file, list_files, and read_file tools to the coder_llm
        coder_with_tools = coder_llm.bind_tools([write_to_file, list_files, read_file])
        
        messages = [system_instruction, user_prompt]
        response = await coder_with_tools.ainvoke(messages)
        
        # Check if the agent initiated any tool calls, and execute them in a loop
        while response.tool_calls:
            # Append the agent's response containing the tool call to the message history
            messages.append(response)
            
            tool_messages = []
            for tool_call in response.tool_calls:
                tool_name = tool_call["name"]
                tool_args = tool_call["args"]
                
                if tool_name == "write_to_file":
                    tool_result = await write_to_file.ainvoke(tool_args)
                elif tool_name == "list_files":
                    tool_result = await list_files.ainvoke(tool_args)
                elif tool_name == "read_file":
                    tool_result = await read_file.ainvoke(tool_args)
                else:
                    tool_result = f"Error: Tool '{tool_name}' not found."
                    
                tool_messages.append(ToolMessage(
                    content=str(tool_result),
                    tool_call_id=tool_call["id"],
                    name=tool_name
                ))
                
            messages.extend(tool_messages)
            
            # Invoke the coder LLM again with tools and the execution results
            response = await coder_with_tools.ainvoke(messages)
            
    finally:
        workspace_ctx.reset(token)
        
    return {
        "messages": [AIMessage(content=response.content, name="Coder")],
        "next_agent": "end",
    }

def routing_router(state: TeamState) -> str:
    """Conditional router – decides the next node based on ``next_agent``."""
    if state.get("next_agent") == "coder":
        return "coder"
    return END

# Build the graph
builder = StateGraph(TeamState)
builder.add_node("pm", pm_agent)
builder.add_node("coder", coder_agent)
builder.add_edge(START, "pm")
builder.add_conditional_edges(
    "pm",
    routing_router,
    {
        "coder": "coder",
        END: END,
    },
)
builder.add_edge("coder", END)

# Compiled graph – used by the FastAPI route layer.
graph = builder.compile()
